name: Arduino lint
on: [push, pull_request]

# https://github.com/marketplace/actions/arduino-arduino-lint-action

jobs:
  arduino-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Run arduino library lint.
        uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
          compliance: strict
